### ISSUE TITLE
Can omission of .call() result in compile error

### ISSUE THREAD

**Issue by longshorej** [lihaoyi/autowire#17]
Hopefully this makes sense. If I'm doing anything stupid please let me know : )

I'm wondering if there's any way to have `call()` be required to compile. I've had a couple occasions already during development where I forgot to call it and finding out why ScalaJS blew up was fairly difficult.

```scala
trait MyApi {
  def now(): Future[Long]
}

val client = new Client(...)[MyApi]

client.now().call() map (l => println("Res: " + l))
client.now() map (l => println("Res: " + l)) // Any ideas on how to make this fail to compile?
```

**Comment by lihaoyi** [comment]
This has happened

**Comment by longshorej** [comment]
Nice! Thanks!
