### ISSUE TITLE
Autowire RPC with REST fallback

### ISSUE THREAD

**Issue by austinrivas** [lihaoyi/autowire#24]
I've been using autowire for a couple days now in an app that I'm building to familiarize myself with scalaJS.

I have working autowire RPC's in my app, but I was wondering if there was a way to use the server side endpoints as REST endpoints if my client app does not have an autowire client configured.

I totally understand if this is outside the scope of this library, but I was wondering if you or anyone else has explored this use case.

**Comment by lihaoyi** [comment]
Yeah just hit them with ajax requests or tcp calls or however you're hitting them in your autowire flow, they'll work just fine

**Comment by lihaoyi** [comment]
(closing, but feel free to reply)
