### ISSUE TITLE
api path

### ISSUE THREAD

**Issue by MasseGuillaume** [lihaoyi/autowire#26]
To avoid typos, Client should have some notion of the api path

https://github.com/lihaoyi/workbench-example-app/blob/autowire/example/js/src/main/scala/example/ScalaJSExample.scala#L13
https://github.com/lihaoyi/workbench-example-app/blob/autowire/example/jvm/src/main/scala/example/Server.scala#L50

**Comment by lihaoyi** [comment]
I do not understand

**Comment by MasseGuillaume** [comment]
The string "api" is duplicated. So if I write "bazinga" at https://github.com/lihaoyi/workbench-example-app/blob/autowire/example/js/src/main/scala/example/ScalaJSExample.scala#L13 I will see a 404 when calling this api endpoint.

**Comment by lihaoyi** [comment]
Yes, but how are you proposing we avoid this? AFAICT the underlying wiring will always be fragile and that's just the way it is

**Comment by MasseGuillaume** [comment]
The string "api" is duplicated. So if I write "bazinga" at https://github.com/lihaoyi/workbench-example-app/blob/autowire/example/js/src/main/scala/example/ScalaJSExample.scala#L13 I will see a 404 when calling this api endpoint.

Do you pickle/unpickle everything in the "/api" enpoint ? So let's say if I add an open file method do I need to split in "/api/list" & "/api/open" ?

**Comment by lihaoyi** [comment]
Could you elaborate? I honestly don't know what you're asking. Have you used autowire?

**Comment by lihaoyi** [comment]
Closing this for now, feel free to ask on the gitter channel if you're still confused...
