### ISSUE TITLE
exception during macro expansion after importing widok packages

### ISSUE THREAD

**Issue by jn73** [lihaoyi/autowire#27]
I'm experimenting with an autowire-based scalajs client. It works as expected as long as i stick to plain scalajs/dom. Now i want to try adding widok (https://widok.github.io/) to the party..

For me, just adding widok as a sbt-dependency to the javascript project  (crossproject) and importing org.widok._ causes autowire to fail compilation with the following error:

[error] /Users/janne/projects/private/gb/example/js/src/main/scala/example/ScalaJSExample.scala:40: exception during macro expansion:
[error] java.lang.AssertionError: assertion failed
[error] 	at scala.Predef$.assert(Predef.scala:151)
[error] 	at upickle.Macros$.macroRImpl(Macros.scala:32)
[error]     Client[Api].chapters().call().map { c =>
[error]                                ^

I don't know if this issue belongs to autowire or widok.. or upickle? Filing it here anyway.

Let me know if I can do anything to assist with logs or debugging. I'm really looking forward to getting these really promising technologies working together :-)

**Comment by tindzk** [comment]
The reason is that one of [Widok's implicits](https://github.com/widok/widok/blob/master/js/src/main/scala/org/widok.scala) conflicts with uPickle. In my projects I solved it by creating a wrapper object:

```scala
package client

import scala.concurrent.Future
import scala.scalajs.concurrent.JSExecutionContext.Implicits.runNow

object Server extends autowire.Client[String, upickle.Reader, upickle.Writer] {
  ...
  def read[Result: upickle.Reader](p: String) = upickle.read[Result](p)
  def write[Result: upickle.Writer](r: Result) = upickle.write(r)
}

object ServerOps {
  import autowire._

  /* IntelliJ erroneously declares this as 'unused import statement'. */
  import upickle._

  object Resource {
    def insert(resource: model.Resource.Insert) =
      Server[Protocol].resource.insert(resource).call()
  }
}
```

**Comment by jn73** [comment]
Thanks for your suggestion. I tried doing something similar but the problem remains.. Perhaps i missed something in the code?

```scala
package se.oobo

import example.Api
import org.scalajs.dom
import scala.concurrent.Future
import scala.scalajs.concurrent.JSExecutionContext.Implicits.runNow

object Server extends autowire.Client[String, upickle.Reader, upickle.Writer] {
  override def doCall(req: Request): Future[String] = {
    dom.ext.Ajax.post(
      url = "/api/" + req.path.mkString("/"),
      data = upickle.write(req.args)
    ).map(_.responseText)
  }

  def read[Result: upickle.Reader](p: String) = upickle.read[Result](p)

  def write[Result: upickle.Writer](r: Result) = upickle.write(r)
}

object ServerOpts {

  import autowire._
  import upickle._

  object Resource {
    def chapters = Server[Api].chapters().call()
  }

}
```

Same problem.. error during macro expansion.

**Comment by tindzk** [comment]
The code is fine. The problem is not related to Widok, but pertains the protocol itself. I came across this assertion a few times before. It fails if an object has members from ``scala.`` for which uPickle doesn't provide any implicits. Would you mind showing me ``Api`` as well as all the types that you're declaring?

**Comment by jn73** [comment]
Sure, it's very basic (just trying to get something to run at this time)

```scala
package example

trait Api {

  case class Chapter(id: Option[Int], title: String)

  def list(path: String): Seq[String]
  def chapters(): Seq[Chapter]
  def chapter(id: Int) : Option[Chapter]

}
```

**Comment by tindzk** [comment]
As far as I know uPickle doesn't support path-dependent types. Try to move ``Chapter`` out of ``Api``. That should do it.

**Comment by jn73** [comment]
That works :) Thanks a lot for your help!

**Comment by lihaoyi** [comment]
@tindzk is right. The error messages have been improved considerably, but not for this case. I don't see us ever being able to support path-dependent types because of the necessity of serializing outer-pointers.

**Comment by jn73** [comment]
Ok @lihaoyi, in all honestly I wasn't aware of path-dependent types.. there is always more to learn with scala :-) Thank you both for all your excellent work with scalajs  and its ecosystem. This surely made working on the client side fun again!
