### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by caente** [lihaoyi/autowire#28]
Hi! I haven't found where is the proper place to set the implicit timeout for sendReceive... so, if I'd like to have a timeout beyond the 60s default, what can I do?

**Comment by bkkoo** [comment]
I would like to know which line of code that define the 60s default timeout. Because I'm also interested in the way to implicit define time out more than or less than 60s.

**Comment by tindzk** [comment]
autowire doesn't have any notion of connections and thereby timeouts. If you're using HTTP, have a look at [``Ajax.post``](http://www.scala-js.org/api/scalajs-dom/0.6/index.html#org.scalajs.dom.extensions.Ajax$) which takes a ``timeout`` parameter.
