### ISSUE TITLE
How to use it with unfiltered?

### ISSUE THREAD

**Issue by freewind** [lihaoyi/autowire#29]
In the [example](https://github.com/lihaoyi/workbench-example-app/blob/autowire/example/jvm/src/main/scala/example/Server.scala), it's using spray on the server side.

I tried to use unfiltered, but not sure how to do it. Could you give some ideas?

Not sure how to write similar code with unfiltered for [following code](https://github.com/lihaoyi/workbench-example-app/tree/autowire/example/jvm/src/main/scala/example#L49):

```scala
 post {
        path("api" / Segments){ s =>
          extract(_.request.entity.asString) { e =>
            complete {
              AutowireServer.route[Api](Server)(
                autowire.Core.Request(s, upickle.read[Map[String, String]](e))
              )
            }
          }
        }
      }
```

**Comment by elacin** [comment]
I know this is months ago @freewind, but i just stumbled over it. I just wrote some unfiltered/autowire glue myself, this is how i did it:

```scala
      case req@ContextPath(_, Seg("api" :: s)) ⇒ 
        val p       = upickle.read[Map[String, String]](Body.string(req))
        val resultF = route(autowire.Core.Request(s, p))

```

I think we should write up a wiki page or something with overall hints and code for integrating autowire with different http and serialization libraries. 
In particular i didn't think it was obvious which part of the url should be threaded through, and that i had to parse the body into a `Map[String, String]` myself

**Comment by lihaoyi** [comment]
Seems solved
