### ISSUE TITLE
File transfer

### ISSUE THREAD

**Issue by mathieuleclaire** [lihaoyi/autowire#30]
Hi, 
how can I do to deal with File transfer with autowire (download and updload) ? What do you recommand ?
Thanks

**Comment by tindzk** [comment]
I wouldn't use Autowire for file transfers because you'd need to encode the data as JSON, which incurs an unnecessary overhead. If you're using Spray, have a look at [this repository](https://github.com/whataboutbob/spray-file-upload).

**Comment by LogicalTime** [comment]
You could do it with boopickle. Would love too be able to have an Akka streams source of Pickleable obj we cts in an API and send the data chunked.
