### ISSUE TITLE
Support for JSON-RPC

### ISSUE THREAD

**Issue by mkotsbak** [lihaoyi/autowire#33]
Would be nice for third party integration with the protocol if some standard protocol like JSON-RPC was used.

Maybe the protocol could be specified by a pluggable protocol module?

**Comment by lihaoyi** [comment]
Sure go for it

**Comment by mkotsbak** [comment]
Todos:
  * `Request.path: Seq[String]` as JSON-RPC requires a string "method" attribute sent.
  * An "id" must be generated, which either could be a counter or a UUID.
  * Return errors must be handled in the "error" attribute, and results in the "results" attribute

The actual conversion to JSON is up to the user, but if it is formatted as JSON-RPC objects/attributes, chances are high that it might generate valid JSON-RPC packets.

**Comment by mkotsbak** [comment]
Another alternative for more REST like API is to check out Endpoints library: http://julienrf.github.io/endpoints/index.html

**Comment by mkotsbak** [comment]
There is another library doing exactly this: https://github.com/shogowada/scala-json-rpc
