### ISSUE TITLE
Authentication, session and identity support

### ISSUE THREAD

**Issue by mkotsbak** [lihaoyi/autowire#34]
Please add a mechanism for authenticating clients, keep the sessions between calls (in case of HTTP example) and getting the identity of the caller.

**Comment by Daxten** [comment]
Wouldn't say autowire is the right library for this. You can create a Router Class by Call with the Request as a parameter and implement it that way

**Comment by lihaoyi** [comment]
@Daxten is right

**Comment by mkotsbak** [comment]
Still you would need to get the identity of the user in the API implementation.

**Comment by lihaoyi** [comment]
That's not autowire's problem. Ask on the mailing list if you want to see what others have done

**Comment by mkotsbak** [comment]
This thread might provide some interesting hints about to do this around Autowire:

https://groups.google.com/forum/m/#!msg/scala-js/0G-SjVqJI0A/mf4M6tR-BQAJ

**Comment by Daxten** [comment]
```
  def api(s: String) = AsyncStack(AuthorityKey -> isLoggedIn) { implicit request =>
    val path = s.split("/")
    request.body.asJson.map { json =>
      AutowireRouter.route[ServerApi](new ServerApiService(dao, loggedIn, ws))(
        autowire.Core.Request(path, read[Map[String, String]](json.toString()))
      ) flatMap (responseData => Future.successful(Ok(responseData)))
    } getOrElse {
      Future.successful(BadRequest)
    }
  }

// routes file:
POST        /api/*path                             controllers.Application.api(path)
```
here is an example, using play2-auth for auth and upickle for serialization, hope this helps

**Comment by mkotsbak** [comment]
Thanks for the Play example!

**Comment by mkotsbak** [comment]
What is AsyncStack?

**Comment by mkotsbak** [comment]
Putting the extra auth data in the implementation class as constructor parameters is nice, but another possibility is probably to use implicit variables that could be catched anywhere it is needed.

**Comment by Daxten** [comment]
Look at play2-auth, AsyncStack is implemented there

**Comment by mkotsbak** [comment]
I made a simple framework/library for this here now, doing almost the same, just a bit more general: https://gist.github.com/mkotsbak/08b808d5152c96b65b4d
