### ISSUE TITLE
Serialization library

### ISSUE THREAD

**Issue by mathieuleclaire** [lihaoyi/autowire#37]
Hi,
I really need to serialize Classes not depending to a sealed trait. Upickle, unfortunately, cannot do this. Is it planned to implement this in upickle or is there an alternative library achieving this working in autowire ?

Thanks
Mathieu

**Comment by cvogt** [comment]
you mean DEPENDING on a sealed trait? cvogt/play-json-extensions has experimental support for sealed trait serialization. Check out https://github.com/cvogt/play-json-extensions/blob/master/src/test/scala/PlayJsonExtensionsTest.scala#L23
We use it with autowire like this:
```
  object Server extends autowire.Server[String, Reads, Writes] with autowire.Serializers[String, Reads, Writes] {
    def read[Result: Reads]( p: String ) = Json.fromJson( Json.parse( p ) ) match {
      case JsSuccess( r, _ ) => r
      case JsError( errors ) => throw new RuntimeException( errors.toString )
    }
    def write[Result: Writes]( r: Result ) = Json.stringify( Json.toJson( r ) )
  }
```

**Comment by lihaoyi** [comment]
Not gonna happen AFAICT, this isn't autowire's problem
