### ISSUE TITLE
Minimal example does not compile with upickle 0.4.4

### ISSUE THREAD

**Issue by jhegedus42** [lihaoyi/autowire#56]
https://github.com/lihaoyi/autowire#minimal-example

<img width="641" alt="screen shot 2016-12-30 at 13 18 56" src="https://cloud.githubusercontent.com/assets/6671476/21564144/95312e12-ce92-11e6-881f-f7e2ae6c5bf0.png">

**Comment by nafg** [comment]
@jhegedus42 it should be updated to `upickle.default.Reader`, same for `Writer`, `read`, and `write`

**Comment by nafg** [comment]
@lihaoyi seems the readme is from the pre-upickle-0.3.0 era :(

**Comment by nafg** [comment]
@lihaoyi I guess the ticket title should be changed to "update documentation for upickle > 0.3.0" or something?
