### ISSUE TITLE
Pickle type for traits in method arguments

### ISSUE THREAD

**Issue by cornerman** [lihaoyi/autowire#59]
Just encountered a problem when using traits as arguments in api methods with boopickle. 

So, I defined the following Api in the backend with a corresponding route:
```scala
sealed trait Tret
case class Clars(id: Int) extends Tret

trait Api {
  def fun(x: Tret): Int
}
```

Then, when calling this method in the frontend: `Client.wire[Api].fun(Clars(12)).call()`.
It generates the following code:
```scala
Client.wire.apply[api.Api].self.doCall(autowire.Core.Request.apply[java.nio.ByteBuffer](collection.this.Seq.apply[String]("api", "Api", "fun"), scala.this.Predef.Map.apply[String, java.nio.ByteBuffer](scala.this.Predef.ArrowAssoc[String]("x").->[java.nio.ByteBuffer](Client.wire.apply[api.Api].self.write[api.Clars](api.Clars.apply(12))
```

Specifically this part (`Client.wire.apply[api.Api].self.write[api.Clars](api.Clars.apply(12))`) is crucial when using boopickle. Our `autowire.Server` defines serialization as:
```scala
object AutowireServer extends autowire.Server[ByteBuffer, Pickler, Pickler] {
  def read[Result: Pickler](p: ByteBuffer) = Unpickle[Result].fromBytes(p)
  def write[Result: Pickler](r: Result) = Pickle.intoBytes(r)
}
```

With `Clars` as type parameter, it will pickle the parameter as a `Clars` and not as a `Tret`. This is why, boopickle is unable to deserialize this parameter in the backend and (probably?) explains why I end up with a `NotImplementedError` in the generated router code.

As a workaround, I can explicitly specify the type: `Client.wire[Api].fun(Clars(12) : Tret).call()`.
But this is very easy to forget without the compiler noticing and it will only result in runtime errors.

Would it be possible to handle this in autowire when calling `write`? So, we could take the parameter type according to the signature of the called method (which would be `Tret` in this example).

**Comment by torstenrudolf** [comment]
excellent, thanks for the explanation, just running into the same problem using circe as the pickler!
