### ISSUE TITLE
Need a license for this project

### ISSUE THREAD

**Issue by lxohi** [lihaoyi/autowire#79]
Hi,
Seems this great project was not under active maintenance, and I'm interested in fork it and publish a patched version for some issues.
But here is no LICENSE file which means technically I was not permitted to publish a patched version.
Would you please generously add a LICENSE file to this project?

**Comment by lihaoyi** [comment]
treat it as MIT

**Comment by lxohi** [comment]
ah, great! Thank you so much :P
