### ISSUE TITLE
Autowire maintenance

### ISSUE THREAD

**Issue by mathieuleclaire** [lihaoyi/autowire#85]
Hi,
the autowire project is really cool to connect seamlessly client and server. And yet it is dying althought 2.13 PR (@MasseGuillaume). Some other upgrades are required for scalajs 1.0. If no one is no longer maintening it, would it be possible to promote some of so that we could merge PR and trying to keep this project up ?
Thanks !

**Comment by lihaoyi** [comment]
@mathieuleclaire I sent you an invite to give you commit access to this repo

**Comment by mathieuleclaire** [comment]
Thanks !

**Comment by godenji** [comment]
This is great, the merged Scala 2.13/Scala.js 1.0 PR is reason enough for a new release -- how is this managed currently?

**Comment by lihaoyi** [comment]
Unless I gave someone creds (I forgot if I did...), you guys probably have to tell me when you a release cut from master, and I'll run `publishSigned` for you

**Comment by mathieuleclaire** [comment]
I commited upgrades for scala 2.13 and scalajs. It compiles fine for 2.12 and 2.13. 2.11 and 2.10 have been dropped since they relied on closed project pickling. However only 9 tests out of 23 passed. These tests are done with upickle, which changed a lot since 0.2.6 release. Maybe the failed tests are caused by changes in the upickle lib. If someone can have a look to it, it would finish the work for this release. Otherwise, I will test directly in my projects (with Boopickle) but I still have to wait for scala 2.13 and scalajs 1.0.1 extra libs upgrades.

**Comment by mathieuleclaire** [comment]
While investigating a bit deeper, I got the Exception (which is not thrown in detail by the tests). All the tests failing are failing because of errors from upickle like this: 
```sh
Invalid(i,upickle.core.Abort: expected number got string)
``` 
Is there any upickle breaking change in the upickle API that could lead to this kind of serilazation error ?

**Comment by mathieuleclaire** [comment]
I fixed the tests.
The only small exception for the Point case class. I always get the following error:

```could not find implicit value for evidence parameter of type upickle.default.Reader[autowire.Point]```
even if I define a manual sealed trait Pickler for Point.

I also updated the travis yml, @lihaoyi, would you reactivate autowire automatic tests on your travis dashboard ?

**Comment by lihaoyi** [comment]
@mathieuleclaire I just activated it

**Comment by mathieuleclaire** [comment]
Really ? I don't see any run. Do we need to activate something from the github side ?

**Comment by mathieuleclaire** [comment]
The CI works, thanks and retourned no errors after merging the PR #87 
@lihaoyi, It's ok for me for realeasing.

**Comment by mathieuleclaire** [comment]
@lihaoyi, would you release this ? A 0.3.0 sounds good to me !
